# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd 
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [6]:
path = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"  # tsv stands for tab-separated values, so in this case you have to use sep="\t"

df = pd.read_csv(path, sep="\t")

### Step 3. Assign it to a variable called chipo.

In [48]:
chipo = df.copy()

### Step 4. See the first 10 entries

In [8]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [10]:
# Solution 1

chipo.shape[0]

4622

In [12]:
# Solution 2

len(chipo)

4622

### Step 6. What is the number of columns in the dataset?

In [13]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [15]:
chipo.columns.to_list()

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. How is the dataset indexed?

In [18]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [34]:

chipo["item_name"].value_counts().idxmax()

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [88]:
chipo.groupby("item_name")["quantity"].sum().max()

np.int64(761)

### Step 11. What was the most ordered item in the choice_description column?

In [36]:
chipo["choice_description"].value_counts().idxmax()

'[Diet Coke]'

### Step 12. How many items were orderd in total?

In [38]:
chipo["choice_description"].value_counts().max()

np.int64(134)

### Step 13. Turn the item price into a float

In [49]:
chipo["item_price"] = chipo["item_price"].apply(lambda x: float(x[1:]))
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

#### Step 13 Check the item price type

In [53]:
chipo["item_price"].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [58]:
chipo["revenue"] = chipo["quantity"] * chipo["item_price"]
tot_revenue = chipo["revenue"].sum()
print(f"the total revenue for the period is ${tot_revenue}")

the total revenue for the period is $39237.02

### Step 15. How many orders were made in the period?

In [80]:
tot_orders = chipo["order_id"].nunique()

print(f"{tot_orders} orders have been made in total")

1834 orders have been made in total

### Step 16. What is the average revenue amount per order?

In [103]:
# Solution 1
chipo.groupby("order_id")["revenue"].sum()

order_id
1       11.56
2       33.96
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: revenue, Length: 1834, dtype: float64

### Step 17. How many different items are sold?

In [91]:
chipo["item_name"].nunique()

50

In [118]:
chipo.groupby("order_id")["quantity"].sum().mean()

np.float64(2.711014176663032)