# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd 

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [12]:
chipo = pd.read_csv(url, sep = "\t")

chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [ ]:
chipo["item_price"] = chipo["item_price"].apply(lambda x: float(x[1:]))

3492

In [18]:
chipo[chipo["item_price"] > 10].drop_duplicates().shape[0]

1123

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [17]:
chipo[["item_name", "item_price"]].sort_values(by = "item_price", ascending = False).drop_duplicates()

                         item_name  item_price
3598  Chips and Fresh Tomato Salsa       44.25
3480                 Carnitas Bowl       35.25
1254               Chicken Burrito       35.00
3601                Veggie Burrito       33.75
409                   Chicken Bowl       32.94
...                            ...         ...
3028                 Side of Chips        1.69
3737                 Bottled Water        1.50
3802             Canned Soft Drink        1.25
4008                   Canned Soda        1.09
2754                 Bottled Water        1.09

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [39]:
chipo.sort_values(by = "item_name").drop_duplicates()
chipo.item_name.unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

### Step 7. What was the quantity of the most expensive item ordered?

In [26]:
idx = chipo["item_price"].idxmax()
z = chipo.loc[idx, ["quantity"]]
print (z)

quantity    15
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [37]:
chipo[chipo["item_name"]== "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [54]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]

      order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
51          23         2  Canned Soda     [Mountain Dew]        2.18
162         73         2  Canned Soda        [Diet Coke]        2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]        2.18
350        150         2  Canned Soda        [Diet Coke]        2.18
352        151         2  Canned Soda        [Coca Cola]        2.18
698        287         2  Canned Soda        [Coca Cola]        2.18
700        288         2  Canned Soda        [Coca Cola]        2.18
909        376         2  Canned Soda     [Mountain Dew]        2.18
1091       450         2  Canned Soda       [Dr. Pepper]        2.18
1092       450         2  Canned Soda        [Coca Cola]        2.18
1944       787         2  Canned Soda       [Dr. Pepper]        2.18
2135       859         2  Canned Soda        [Diet Coke]        2.18
2235       901         4  Canned Soda           [Sprite]        4.36
2905      1156         2  Canned Soda        [Coca Cola]        2.18
2906      1156         2  Canned Soda           [Sprite]        2.18
3152      1258         2  Canned Soda       [Dr. Pepper]        2.18
3364      1349         2  Canned Soda        [Coca Cola]        2.18
3592      1440         2  Canned Soda        [Diet Coke]        2.18
3866      1550         2  Canned Soda     [Mountain Dew]        2.18